services:
  - type: web
    name: braindocs
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_BASE_URL
        value: https://braindocs-7qqx.onrender.com
      - key: STRIPE_PRICE_SINGLE
        value: price_1U1ekKPOPXDmUKH9VplAoeGZ
      - key: STRIPE_PRICE_PRO
        value: price_1U1ekLPOPXDmUKH9ZFZ6V7PL
      - key: STRIPE_PRICE_LIFETIME
        value: price_1U1ekMPOPXDmUKH9zzpSdrwU
      - key: GEMINI_API_KEY
        sync: false
      - key: GMAIL_USER
        value: 1034jcd@gmail.com
      - key: OWNER_EMAIL
        value: 1034jcd@gmail.com
